#!/usr/bin/env python3
r"""Pure spectral AD pair/self closure for Figure 5.

The target-conditioned pair amplitude for target class ``a`` is

.. math::

   \mu_a(q) = \left\langle N_a^{-1}\sum_{i\in a}
   \left[e^{i q r_i}\rho(q)-q_i\right]\right\rangle.

Together with ``S_tag``, it gives a conditional-mean decomposition of the
distinct-particle pair field.  The zero-mean fluctuation is retained in the
diagonal AD cell-moment estimator.  The coherent field generated by
``mu_a`` is combined with the raw mesh self response to form the complete
all-source pair field, including ``i=j``.  The production self-correction
field is then added on one mesh cell *before* its norm is formed.  Equivalently,
the distinct-source pair field is added to the residual-self field.  Both
decompositions are evaluated and checked componentwise.  This retains the
pair/self cross term while remaining a structure-spectrum contraction: no
mesh force, direct-band force, reference force, or particlewise force
difference is evaluated.

The coherent source-alias sum contains the zero alias and the six nearest
face aliases.  The fluctuation term retains the all-alias homogeneous
baseline and the separately controlled finite-shell ``S_tag`` correction.
"""

from __future__ import annotations

import math
from dataclasses import dataclass

import numpy as np

import fixed_ik_reference as ikref
from ad_operator_audit import ad_operator_reference as adref


FACE_ALIASES = np.asarray(
    (
        (0, 0, 0),
        (1, 0, 0),
        (-1, 0, 0),
        (0, 1, 0),
        (0, -1, 0),
        (0, 0, 1),
        (0, 0, -1),
    ),
    dtype=np.int64,
)
FINUFFT_TILE_WIDTH = 128


@dataclass(frozen=True)
class StructureSpectra:
    """One-frame structural inputs for the joint AD theory."""

    tagged_pair: np.ndarray
    ordinary_charge: np.ndarray
    conditional_pair_mean: np.ndarray
    charge_classes: np.ndarray
    class_counts: np.ndarray


@dataclass(frozen=True)
class JointCellMoments:
    """Cell-averaged coherent pair/self moments for several spectra."""

    coherent_pair_mean_square: np.ndarray
    residual_self_mean_square: np.ndarray
    pair_self_dot_mean: np.ndarray
    all_source_pair_mean_square: np.ndarray
    self_correction_mean_square: np.ndarray
    all_source_pair_self_correction_dot_mean: np.ndarray
    coherent_joint_mean_square: np.ndarray
    equivalent_decomposition_component_max_abs: float
    maximum_imaginary_component: float
    production_real_projection_applied: bool
    quadratic_identity_max_abs: float
    alias_vectors: np.ndarray
    quadrature_order_per_half: int


def _canonical_modes_with_conjugation(
    modes: np.ndarray,
) -> tuple[np.ndarray, np.ndarray]:
    values = np.asarray(modes, dtype=np.int64).copy()
    nonzero = values != 0
    if np.any(~np.any(nonzero, axis=1)):
        raise ValueError("the zero mode cannot enter a pair spectrum")
    first = np.argmax(nonzero, axis=1)
    reflected = values[np.arange(len(values)), first] < 0
    values[reflected] *= -1
    return values, reflected


def canonical_mode_union(*blocks: np.ndarray) -> np.ndarray:
    """Return inversion-canonical nonzero modes from all input blocks."""

    usable = [np.asarray(block, dtype=np.int64) for block in blocks if len(block)]
    if not usable:
        raise ValueError("at least one nonempty mode block is required")
    canonical, _ = _canonical_modes_with_conjugation(np.concatenate(usable))
    return np.unique(canonical, axis=0)


def face_alias_modes(operator: adref.ADOperator) -> np.ndarray:
    """Return all physical source modes used by the coherent closure."""

    active = np.argwhere(operator.kernel != 0.0)
    axis = np.rint(np.fft.fftfreq(operator.mesh) * operator.mesh).astype(np.int64)
    base = np.column_stack([axis[active[:, dim]] for dim in range(3)])
    modes = (
        base[:, None, :] + operator.mesh * FACE_ALIASES[None, :, :]
    ).reshape(-1, 3)
    return canonical_mode_union(modes)


def lookup_conditional_pair_mean(
    frozen_modes: np.ndarray,
    conditional_pair_mean: np.ndarray,
    query_modes: np.ndarray,
    *,
    mode_lookup: dict[tuple[int, int, int], int] | None = None,
) -> np.ndarray:
    """Look up complex conditional amplitudes with inversion symmetry."""

    stored_modes = np.asarray(frozen_modes, dtype=np.int64)
    values = np.asarray(conditional_pair_mean, dtype=np.complex128)
    if values.shape[-1] != len(stored_modes):
        raise ValueError("conditional spectrum and mode table disagree")
    canonical, reflected = _canonical_modes_with_conjugation(query_modes)
    lookup = mode_lookup
    if lookup is None:
        lookup = {
            tuple(mode): index for index, mode in enumerate(stored_modes.tolist())
        }
    try:
        indices = np.asarray([lookup[tuple(mode)] for mode in canonical], dtype=np.int64)
    except KeyError as error:
        raise KeyError(f"query mode is absent from the frozen spectrum: {error}") from error
    selected = values[..., indices]
    return np.where(reflected, np.conjugate(selected), selected)


def _direct_transforms(
    charges: np.ndarray,
    coordinates: np.ndarray,
    box_length: float,
    modes: np.ndarray,
    class_masks: list[np.ndarray],
    chunk_size: int,
) -> tuple[np.ndarray, np.ndarray, list[np.ndarray]]:
    frac = np.mod(coordinates, box_length) / box_length
    rho1 = np.empty(len(modes), dtype=np.complex128)
    rho3 = np.empty_like(rho1)
    targets = [np.empty_like(rho1) for _ in class_masks]
    for start in range(0, len(modes), chunk_size):
        stop = min(start + chunk_size, len(modes))
        phase = np.exp(
            -2j * math.pi * (frac @ np.asarray(modes[start:stop]).T)
        )
        rho1[start:stop] = charges @ phase
        rho3[start:stop] = (charges**3) @ phase
        for result, mask in zip(targets, class_masks):
            result[start:stop] = mask.astype(np.float64) @ phase
    return rho1, rho3, targets


def _finufft_transforms(
    charges: np.ndarray,
    coordinates: np.ndarray,
    box_length: float,
    modes: np.ndarray,
    class_masks: list[np.ndarray],
    tile_width: int = FINUFFT_TILE_WIDTH,
) -> tuple[np.ndarray, np.ndarray, list[np.ndarray]]:
    try:
        import finufft
    except ImportError as error:
        raise RuntimeError(
            "Figure-5 spectrum freezing requires FINUFFT; install requirements.txt"
        ) from error

    frac = np.mod(coordinates, box_length) / box_length
    angles = [
        np.ascontiguousarray(2.0 * math.pi * (frac[:, dim] - 0.5))
        for dim in range(3)
    ]
    if tile_width < 16 or tile_width % 2:
        raise ValueError("FINUFFT tile width must be an even integer >= 16")
    kwargs = {"eps": 1.0e-12, "isign": -1, "nthreads": 1}

    # One batched transform shares the expensive type-3 plan across all target
    # charge classes.  rho and rho_3 are exact linear combinations of those
    # class-indicator transforms, so separate NUFFTs would be redundant.
    class_strengths = np.ascontiguousarray(
        np.stack(class_masks).astype(np.complex128)
    )
    # A single type-3 plan spanning every alias shell scales with the cube of
    # the largest frequency, even though the requested integer modes are
    # sparse.  Tile frequency space and shift each tile to the origin.  The
    # exact identity exp(-i (k+c).x) = exp(-i c.x) exp(-i k.x) makes this a
    # memory-bounded reorganization, not an approximation.
    indices = np.asarray(modes, dtype=np.int64)
    half = tile_width // 2
    tile_keys = np.floor_divide(indices + half, tile_width)
    unique_tiles, inverse = np.unique(tile_keys, axis=0, return_inverse=True)
    permutation = np.argsort(inverse, kind="stable")
    boundaries = np.searchsorted(
        inverse[permutation], np.arange(len(unique_tiles) + 1)
    )
    transformed = np.empty(
        (len(class_masks), len(indices)), dtype=np.complex128
    )
    for tile_index, tile_key in enumerate(unique_tiles):
        selected = permutation[boundaries[tile_index] : boundaries[tile_index + 1]]
        center = np.asarray(tile_key, dtype=np.int64) * tile_width
        local_modes = indices[selected] - center
        modulation = np.exp(
            -1j
            * (
                center[0] * angles[0]
                + center[1] * angles[1]
                + center[2] * angles[2]
            )
        )
        local_strengths = np.ascontiguousarray(
            class_strengths * modulation[None, :]
        )
        local_targets = [
            np.ascontiguousarray(local_modes[:, dim], dtype=np.float64)
            for dim in range(3)
        ]
        transformed[:, selected] = np.atleast_2d(
            finufft.nufft3d3(
                *angles,
                local_strengths,
                *local_targets,
                **kwargs,
            )
        )
    class_charges = np.asarray(
        [charges[np.flatnonzero(mask)[0]] for mask in class_masks],
        dtype=np.float64,
    )
    rho1 = class_charges @ transformed
    rho3 = (class_charges**3) @ transformed
    target_transforms = [transformed[index] for index in range(len(class_masks))]
    # The coordinate shift contributes the same unit-modulus phase to every
    # transform.  All quantities below are phase-cancelling products.
    return rho1, rho3, target_transforms


def evaluate_structure_spectra(
    q: np.ndarray,
    xyz: np.ndarray,
    box_length: float,
    modes: np.ndarray,
    *,
    backend: str = "finufft",
    chunk_size: int = 512,
) -> StructureSpectra:
    """Evaluate ``S_tag``, ``S_q``, and charge-class conditional means."""

    charges = np.asarray(q, dtype=np.float64)
    coordinates = np.asarray(xyz, dtype=np.float64)
    indices = np.asarray(modes, dtype=np.int64)
    if coordinates.shape != (len(charges), 3):
        raise ValueError("xyz must have shape (len(q),3)")
    if indices.ndim != 2 or indices.shape[1] != 3:
        raise ValueError("modes must have shape (n,3)")
    if np.any(~np.any(indices != 0, axis=1)):
        raise ValueError("the zero mode is not a Figure-5 structural input")
    if chunk_size < 1:
        raise ValueError("chunk_size must be positive")

    charge_classes = np.unique(charges)
    class_masks = [charges == value for value in charge_classes]
    class_counts = np.asarray([np.count_nonzero(mask) for mask in class_masks])
    if backend == "finufft":
        rho1, rho3, target_transforms = _finufft_transforms(
            charges, coordinates, box_length, indices, class_masks
        )
    elif backend == "direct":
        rho1, rho3, target_transforms = _direct_transforms(
            charges,
            coordinates,
            box_length,
            indices,
            class_masks,
            chunk_size,
        )
    else:
        raise ValueError(f"unknown structure-spectrum backend: {backend}")

    q2 = float(np.sum(charges**2))
    q4 = float(np.sum(charges**4))
    denominator = q2 * q2 - q4
    if denominator <= 0.0:
        raise ValueError("at least two nonzero charges are required")
    tagged_numerator = q2 * np.abs(rho1) ** 2 + q4
    tagged_numerator -= 2.0 * np.real(rho1 * np.conjugate(rho3))
    roundoff = 256.0 * np.finfo(np.float64).eps * max(
        denominator, float(np.max(np.abs(tagged_numerator))), 1.0
    )
    if float(np.min(tagged_numerator)) < -roundoff:
        raise FloatingPointError("target-conditioned pair spectrum became negative")
    tagged = np.maximum(tagged_numerator, 0.0) / denominator
    ordinary = np.abs(rho1) ** 2 / q2
    conditional = np.asarray(
        [
            (rho1 * np.conjugate(target) - count * charge_value) / count
            for charge_value, count, target in zip(
                charge_classes, class_counts, target_transforms
            )
        ],
        dtype=np.complex128,
    )
    return StructureSpectra(
        tagged_pair=np.asarray(tagged, dtype=np.float64),
        ordinary_charge=np.asarray(ordinary, dtype=np.float64),
        conditional_pair_mean=conditional,
        charge_classes=np.asarray(charge_classes, dtype=np.float64),
        class_counts=np.asarray(class_counts, dtype=np.int64),
    )


def coherent_s_tag(
    q: np.ndarray,
    charge_classes: np.ndarray,
    class_counts: np.ndarray,
    conditional_pair_mean: np.ndarray,
) -> np.ndarray:
    """Return the conditional-mean part of ``S_tag``."""

    charges = np.asarray(q, dtype=np.float64)
    classes = np.asarray(charge_classes, dtype=np.float64)
    counts = np.asarray(class_counts, dtype=np.float64)
    conditional = np.asarray(conditional_pair_mean, dtype=np.complex128)
    if conditional.shape[-2] != len(classes):
        raise ValueError("conditional pair spectrum has the wrong class axis")
    denominator = float(np.sum(charges**2) ** 2 - np.sum(charges**4))
    numerator = np.sum(
        counts.reshape((1,) * (conditional.ndim - 2) + (-1, 1))
        * classes.reshape((1,) * (conditional.ndim - 2) + (-1, 1)) ** 2
        * np.abs(conditional) ** 2,
        axis=-2,
    )
    return np.asarray(numerator / denominator, dtype=np.float64)


def _cell_quadrature(order_per_half: int) -> tuple[np.ndarray, np.ndarray]:
    if order_per_half < 8:
        raise ValueError("cell quadrature order per half must be at least 8")
    nodes, weights = np.polynomial.legendre.leggauss(order_per_half)
    fraction_parts = []
    weight_parts = []
    for lo, hi in ((0.0, 0.5), (0.5, 1.0)):
        fraction_parts.append(0.5 * (hi - lo) * nodes + 0.5 * (hi + lo))
        weight_parts.append(0.5 * (hi - lo) * weights)
    return np.concatenate(fraction_parts), np.concatenate(weight_parts)


def coherent_pair_self_cell_moments(
    *,
    q: np.ndarray,
    frozen_modes: np.ndarray,
    conditional_pair_mean: np.ndarray,
    charge_classes: np.ndarray,
    class_counts: np.ndarray,
    operator: adref.ADOperator,
    real_coeff: np.ndarray,
    self_correction: np.ndarray,
    quadrature_order_per_half: int,
) -> JointCellMoments:
    """Add coherent pair and residual-self fields before cell averaging.

    ``conditional_pair_mean`` may have any leading population axis and must
    end in ``(nclass,nmode)``.  Figure 5 passes the full pilot mean followed
    by its five block means in one batched contraction.
    """

    charges = np.asarray(q, dtype=np.float64)
    classes = np.asarray(charge_classes, dtype=np.float64)
    counts = np.asarray(class_counts, dtype=np.float64)
    conditional = np.asarray(conditional_pair_mean, dtype=np.complex128)
    if conditional.ndim < 2 or conditional.shape[-2:] != (
        len(classes),
        len(frozen_modes),
    ):
        raise ValueError("conditional pair spectrum has incompatible dimensions")
    if not np.array_equal(
        np.asarray([np.count_nonzero(charges == value) for value in classes]),
        np.asarray(class_counts, dtype=np.int64),
    ):
        raise ValueError("frozen target charge classes do not match the charge array")
    leading_shape = conditional.shape[:-2]
    flat = conditional.reshape((-1, len(classes), len(frozen_modes)))
    mode_lookup = {
        tuple(mode): index
        for index, mode in enumerate(np.asarray(frozen_modes, dtype=np.int64).tolist())
    }

    fractions, weights = _cell_quadrature(quadrature_order_per_half)
    response_all = adref.cell_responses_1d(
        fractions,
        operator.mesh,
        operator.box_length,
        operator.order,
        np.asarray(real_coeff, dtype=np.float64),
    )
    raw_self = adref.ad_self_response_cell_grid(
        fractions, operator, np.asarray(real_coeff, dtype=np.float64)
    )
    correction = np.asarray(self_correction, dtype=np.float64)
    if correction.shape != (2,):
        raise ValueError("self correction must contain two harmonic coefficients")
    one = correction[0] * np.sin(2.0 * math.pi * fractions)
    one += correction[1] * np.sin(4.0 * math.pi * fractions)
    correction_grid = np.empty_like(raw_self)
    correction_grid[..., 0] = one[:, None, None]
    correction_grid[..., 1] = one[None, :, None]
    correction_grid[..., 2] = one[None, None, :]
    residual_unit = raw_self - correction_grid

    active = np.argwhere(operator.kernel != 0.0)
    axis = np.rint(np.fft.fftfreq(operator.mesh) * operator.mesh).astype(np.int64)
    active_modes = np.column_stack([axis[active[:, dim]] for dim in range(3)])
    compact_axis = np.arange(
        int(np.min(active_modes)), int(np.max(active_modes)) + 1, dtype=np.int64
    )
    compact_lookup = {int(value): index for index, value in enumerate(compact_axis)}
    compact_indices = np.asarray(
        [[compact_lookup[int(value)] for value in mode] for mode in active_modes],
        dtype=np.int64,
    )
    array_indices = np.asarray(
        [int(np.flatnonzero(axis == value)[0]) for value in compact_axis],
        dtype=np.int64,
    )
    response = adref.CellResponses1D(
        source=response_all.source[array_indices],
        gather=response_all.gather[array_indices],
        gradient=response_all.gradient[array_indices],
    )

    h = operator.box_length / operator.mesh
    _, k1, kx, ky, kz, _ = ikref.reciprocal_arrays(
        operator.mesh, operator.box_length
    )
    alias_axis = np.arange(-1, 2, dtype=np.int64)
    alias_wave = k1[:, None] + (2.0 * math.pi / h) * alias_axis[None, :]
    source1 = adref.actual_window_transforms_1d(
        alias_wave, h, operator.order, np.asarray(real_coeff, dtype=np.float64)
    ).source

    shape3 = (len(compact_axis),) * 3
    field = np.zeros(
        (len(flat), len(classes), len(fractions), len(fractions), len(fractions), 3),
        dtype=np.complex128,
    )
    active_green = operator.green[tuple(active.T)]
    for alias in FACE_ALIASES:
        physical_modes = active_modes + operator.mesh * alias
        mu = lookup_conditional_pair_mean(
            frozen_modes, flat, physical_modes, mode_lookup=mode_lookup
        )
        ax, ay, az = alias
        source_weight = (
            source1[active[:, 0], ax + 1]
            * source1[active[:, 1], ay + 1]
            * source1[active[:, 2], az + 1]
        )
        compact_coeff = np.zeros(
            (len(flat), len(classes), *shape3), dtype=np.complex128
        )
        compact_coeff[
            :,
            :,
            compact_indices[:, 0],
            compact_indices[:, 1],
            compact_indices[:, 2],
        ] = mu * (active_green * source_weight)[None, None, :]
        phases = [
            np.exp(-2j * math.pi * int(alias[dim]) * fractions)
            for dim in range(3)
        ]
        ordinary = [response.gather * phase for phase in phases]
        derivative = [response.gradient * phase for phase in phases]
        field[..., 0] += np.einsum(
            "uvijk,ia,jb,kc->uvabc",
            compact_coeff,
            derivative[0],
            ordinary[1],
            ordinary[2],
            optimize=True,
        )
        field[..., 1] += np.einsum(
            "uvijk,ia,jb,kc->uvabc",
            compact_coeff,
            ordinary[0],
            derivative[1],
            ordinary[2],
            optimize=True,
        )
        field[..., 2] += np.einsum(
            "uvijk,ia,jb,kc->uvabc",
            compact_coeff,
            ordinary[0],
            ordinary[1],
            derivative[2],
            optimize=True,
        )

    base_mu = lookup_conditional_pair_mean(
        frozen_modes, flat, active_modes, mode_lookup=mode_lookup
    )
    active_kernel = operator.kernel[tuple(active.T)]
    wavevectors = np.column_stack(
        (kx[tuple(active.T)], ky[tuple(active.T)], kz[tuple(active.T)])
    )
    continuum = np.einsum(
        "m,uvm,md->uvd",
        1j * active_kernel,
        base_mu,
        wavevectors,
        optimize=True,
    )
    field += continuum[:, :, None, None, None, :]
    field *= (
        ikref.COULOMB_REAL
        * classes[None, :, None, None, None, None]
        / operator.box_length**3
    )
    imaginary_max = float(np.max(np.abs(field.imag), initial=0.0))
    # Production forms a real potential with ``ifftn(...).real`` before the
    # real-valued AD stencil derivative is gathered.  Project here at the
    # same point in the operator.  This matters for the self-conjugate
    # Nyquist slots of even meshes; the discarded component is retained as a
    # diagnostic rather than interpreted as a physical force.
    pair = field.real
    raw_self_field = (
        classes[:, None, None, None, None] ** 2
        * raw_self[None, ...]
    )
    self_correction_field = (
        -classes[:, None, None, None, None] ** 2
        * correction_grid[None, ...]
    )
    residual_self_field = (
        classes[:, None, None, None, None] ** 2
        * residual_unit[None, ...]
    )
    all_source_pair = pair + raw_self_field[None, ...]
    joint_all_source = all_source_pair + self_correction_field[None, ...]
    joint_residual = pair + residual_self_field[None, ...]
    decomposition_difference = float(
        np.max(np.abs(joint_all_source - joint_residual), initial=0.0)
    )
    if decomposition_difference > 2.0e-13 * max(
        float(np.max(np.abs(joint_residual), initial=0.0)), 1.0
    ):
        raise FloatingPointError(
            "all-source and residual-self decompositions disagree"
        )
    joint = joint_all_source
    weight3 = np.einsum("a,b,c->abc", weights, weights, weights)

    def class_cell_mean_square(values: np.ndarray) -> np.ndarray:
        return np.einsum(
            "abc,uvabcd,uvabcd->uv", weight3, values, values, optimize=True
        )

    pair2_by_class = class_cell_mean_square(pair)
    all_source_pair2_by_class = class_cell_mean_square(all_source_pair)
    joint2_by_class = class_cell_mean_square(joint)
    self2_by_class = np.einsum(
        "abc,vabcd,vabcd->v",
        weight3,
        residual_self_field,
        residual_self_field,
        optimize=True,
    )
    self_correction2_by_class = np.einsum(
        "abc,vabcd,vabcd->v",
        weight3,
        self_correction_field,
        self_correction_field,
        optimize=True,
    )
    cross_by_class = np.einsum(
        "abc,uvabcd,vabcd->uv",
        weight3,
        pair,
        residual_self_field,
        optimize=True,
    )
    all_source_cross_by_class = np.einsum(
        "abc,uvabcd,vabcd->uv",
        weight3,
        all_source_pair,
        self_correction_field,
        optimize=True,
    )
    class_probability = counts / np.sum(counts)
    pair2 = np.einsum("uv,v->u", pair2_by_class, class_probability)
    all_source_pair2 = np.einsum(
        "uv,v->u", all_source_pair2_by_class, class_probability
    )
    self2_scalar = float(np.dot(self2_by_class, class_probability))
    self2 = np.full(len(flat), self2_scalar)
    self_correction2_scalar = float(
        np.dot(self_correction2_by_class, class_probability)
    )
    self_correction2 = np.full(len(flat), self_correction2_scalar)
    cross = np.einsum("uv,v->u", cross_by_class, class_probability)
    all_source_cross = np.einsum(
        "uv,v->u", all_source_cross_by_class, class_probability
    )
    joint2 = np.einsum("uv,v->u", joint2_by_class, class_probability)
    identity = np.abs(joint2 - (pair2 + self2 + 2.0 * cross))
    identity_max = float(np.max(identity, initial=0.0))
    if identity_max > 2.0e-12 * max(
        float(np.max(joint2, initial=0.0)),
        float(np.max(pair2, initial=0.0)),
        self2_scalar,
        1.0e-300,
    ):
        raise FloatingPointError("coherent pair/self quadratic identity failed")
    if float(np.min(joint2)) < -1.0e-18:
        raise FloatingPointError("coherent pair/self mean square became negative")
    all_source_identity = np.abs(
        joint2
        - (
            all_source_pair2
            + self_correction2
            + 2.0 * all_source_cross
        )
    )
    all_source_identity_max = float(np.max(all_source_identity, initial=0.0))
    if all_source_identity_max > 2.0e-12 * max(
        float(np.max(joint2, initial=0.0)),
        float(np.max(all_source_pair2, initial=0.0)),
        self_correction2_scalar,
        1.0e-300,
    ):
        raise FloatingPointError("all-source pair/self quadratic identity failed")

    output_shape = leading_shape or ()
    return JointCellMoments(
        coherent_pair_mean_square=pair2.reshape(output_shape),
        residual_self_mean_square=self2.reshape(output_shape),
        pair_self_dot_mean=cross.reshape(output_shape),
        all_source_pair_mean_square=all_source_pair2.reshape(output_shape),
        self_correction_mean_square=self_correction2.reshape(output_shape),
        all_source_pair_self_correction_dot_mean=all_source_cross.reshape(
            output_shape
        ),
        coherent_joint_mean_square=np.maximum(joint2, 0.0).reshape(output_shape),
        equivalent_decomposition_component_max_abs=decomposition_difference,
        maximum_imaginary_component=imaginary_max,
        production_real_projection_applied=True,
        quadratic_identity_max_abs=max(identity_max, all_source_identity_max),
        alias_vectors=FACE_ALIASES.copy(),
        quadrature_order_per_half=quadrature_order_per_half,
    )
